// GTA IV - The Lost and Damned (TLAD) DLC
// File automatically generated by fshasher

#include <utility>

extern const uint64_t TLADHashes[];
extern const std::pair<const char *, uint32_t> TLADFiles[];
extern const size_t TLADFilesSize;

const uint64_t TLADHashes[] = {
    0ULL,  // default.xex
};

const std::pair<const char *, uint32_t> TLADFiles[] = {
    { "default.xex", 0 },
};

const size_t TLADFilesSize = std::size(TLADFiles);
