// GTA IV - The Ballad of Gay Tony (TBOGT) DLC
// File automatically generated by fshasher

#include <utility>

extern const uint64_t TBOGTHashes[];
extern const std::pair<const char *, uint32_t> TBOGTFiles[];
extern const size_t TBOGTFilesSize;

const uint64_t TBOGTHashes[] = {
    0ULL,  // default.xex
};

const std::pair<const char *, uint32_t> TBOGTFiles[] = {
    { "default.xex", 0 },
};

const size_t TBOGTFilesSize = std::size(TBOGTFiles);
