// GTA IV Base Game Files
// File automatically generated by fshasher

#include <utility>

extern const uint64_t GameHashes[];
extern const std::pair<const char *, uint32_t> GameFiles[];
extern const size_t GameFilesSize;

// XXH3-64 hashes for GTA IV Xbox 360 disc content
// Hash count per file allows multiple valid versions (NTSC, PAL, etc.)
const uint64_t GameHashes[] = {
    2823947441600373906ULL,  // default.xex — USA retail 1.00
};

// GTA IV Xbox 360 base game files
// Format: { "filename", hash_count } where hash_count = number of valid hashes
// hash_count = 0 means skip hash validation (file presence still required)
const std::pair<const char *, uint32_t> GameFiles[] = {
    { "default.xex", 1 },
    { "audio.rpf", 0 },
    { "common.rpf", 0 },
    { "xbox360.rpf", 0 },
};

const size_t GameFilesSize = std::size(GameFiles);
