// Generated by libserver/tools/generate_gta4_stat_schema.py. Do not edit.
// Source: gta_iv/xex_excavation/resources/545407F2
// Resource SHA-256: ddfa234bc8d6ab587549aa8bee67d550c5ba4caab92eccd6a00e21f35ddc275c
#pragma once

#include <cstddef>
#include <cstdint>
#include <span>

namespace libserver {

enum class StatWireType : std::uint8_t {
  kInt32,
  kInt64,
  kUnicode,
};

enum class StatAggregation : std::uint8_t {
  kSum,
  kMin,
  kLast,
};

struct Gta4StatFieldDescriptor {
  std::uint32_t view_id;
  std::uint32_t property_id;
  StatWireType wire_type;
  StatAggregation aggregation;
};

struct Gta4StatAttributeMapping {
  std::uint32_t view_id;
  std::uint16_t attribute_id;
  std::uint32_t property_id;
};

inline constexpr std::size_t kGta4ExtractedStatViewCount = 157;
inline constexpr std::size_t kGta4ExtractedStatFieldCount = 1232;
inline constexpr std::size_t kGta4ExtractedStatAttributeMappingCount =
    1232;
inline constexpr std::size_t kGta4InternalCompatibilityStatFieldCount = 1;

// The trusted embedded XLAST schema, excluding internal compatibility policy.
[[nodiscard]] std::span<const Gta4StatFieldDescriptor> Gta4ExtractedStatFields() noexcept;

// Internal-only additions absent from the trusted embedded XLAST schema.
[[nodiscard]] std::span<const Gta4StatFieldDescriptor>
Gta4InternalCompatibilityStatFields() noexcept;

// Searches the extracted schema first, then the separate compatibility table.
[[nodiscard]] const Gta4StatFieldDescriptor* FindGta4StatField(
    std::uint32_t view_id, std::uint32_t property_id) noexcept;

// Trusted XLAST mappings, sorted by (view_id, attribute_id). Internal
// compatibility fields have no mapping unless the embedded XLAST defines one.
[[nodiscard]] std::span<const Gta4StatAttributeMapping>
Gta4ExtractedStatAttributeMappings() noexcept;

[[nodiscard]] const Gta4StatAttributeMapping* FindGta4StatAttributeById(
    std::uint32_t view_id, std::uint16_t attribute_id) noexcept;
[[nodiscard]] const Gta4StatAttributeMapping* FindGta4StatAttributeByPropertyId(
    std::uint32_t view_id, std::uint32_t property_id) noexcept;

[[nodiscard]] std::size_t Gta4StatViewCount() noexcept;
// Includes extracted and explicitly separate internal compatibility descriptors.
[[nodiscard]] std::size_t Gta4StatFieldCount() noexcept;
[[nodiscard]] bool ValidateGta4StatSchema() noexcept;

}  // namespace libserver
