#pragma once

#include "user/config.h"
#include <plume_render_interface.h>

using namespace plume;

namespace PostProcess {

// Shader hashes for post-process shaders (computed from HLSL source at build time)
// These must match the hashes generated by XenosRecomp for postprocess/*.hlsl
namespace ShaderHash {
    // Fullscreen vertex shader
    constexpr uint64_t FullscreenVS = 0x2E0C3E65F83551D4ULL;
    
    // SMAA shaders
    constexpr uint64_t SMAAEdgeDetectPS = 0xBB3171DE755EADDAULL;
    constexpr uint64_t SMAABlendPS = 0xCBF1A03E73FF920FULL;
    
    // TAA shader
    constexpr uint64_t TAAPS = 0x23B41EED42846B3FULL;
    
    // FSR 1.0 shaders
    constexpr uint64_t FSR1EASUPS = 0xDB4863B0C31A22EFULL;
    constexpr uint64_t FSR1RCASPS = 0xB6836B8A33B66FB0ULL;
    
    // Motion blur shaders
    constexpr uint64_t MotionBlurCameraPS = 0x8ADA07D974D45D0FULL;
    constexpr uint64_t MotionBlurEnhancedPS = 0x26C20A94DAD70E23ULL;
    
    // Chromatic aberration shader
    constexpr uint64_t ChromaticAberrationPS = 0xC8212C3B45221B3DULL;
    
    // Film grain shader
    constexpr uint64_t FilmGrainPS = 0xBBBBA40C868BCC1ULL;
    
    // Depth of field shader
    constexpr uint64_t DOFPS = 0xD1ED440EAEF01028ULL;
}

// AA system state
struct AAState {
    bool initialized = false;
    EModernAA currentMode = EModernAA::Off;
    
    // TAA specific state
    uint32_t frameIndex = 0;
    float jitterX = 0.0f;
    float jitterY = 0.0f;
    float prevJitterX = 0.0f;
    float prevJitterY = 0.0f;
    
    // Dynamic resolution state
    float currentResolutionScale = 1.0f;
    float targetFrameTime = 16.67f;  // 60fps
    float lastFrameTime = 0.0f;
};

// Initialize AA system (called from Video::Initialize)
void InitializeAA();

// Update AA state for new frame (called from Video::Present before rendering)
void UpdateAA(float deltaTime);

// Apply AA post-processing (called from Video::Present with frame resources)
// Returns true if AA was applied, false if passthrough
// Full version with all required parameters for actual dispatch
bool ApplyAA(RenderCommandList* commandList, 
             RenderTexture* colorTexture,
             RenderTexture* depthTexture,
             RenderTexture* motionTexture,
             RenderTexture* outputTexture,
             uint32_t inputWidth, uint32_t inputHeight,
             uint32_t outputWidth, uint32_t outputHeight);

// Legacy overload for backwards compatibility - always returns false
bool ApplyAA();

// Get current jitter offset for TAA (applied to projection matrix)
void GetTAAJitter(float& outJitterX, float& outJitterY);

// Get current resolution scale for dynamic resolution
float GetResolutionScale();

// Get SSAA multiplier from config
float GetSSAAMultiplier();

// Shutdown AA system
void ShutdownAA();

// Check if specific AA mode is actually available (not just configured)
bool IsModeAvailable(EModernAA mode);

// Get list of available AA modes for UI
const char* GetModeStatusString(EModernAA mode);

// Global AA state
extern AAState g_aaState;

} // namespace PostProcess
