// Auto-generated by tools/generate_sps_table.py
// Do not edit manually.
#pragma once

#include <cstdint>
#include <cstddef>

struct SpsParamEntry {
    const char* name;
    float value;
};

struct SpsPresetEntry {
    const char* spsName;       // e.g. "gta_vehicle_paint1"
    const char* fxcName;       // e.g. "gta_vehicle_paint1" (the shader keyword value)
    uint8_t drawBucket;        // __rage_drawbucket value (0=default opaque)
    uint8_t paramCount;        // number of float parameters
    const SpsParamEntry* params; // pointer to parameter array (or nullptr)
};

static const SpsParamEntry s_spsParams_gta_vehicle_chrome[] = {
    { "SpecularColor", 0.2f },
    { "Specular", 180.0f },
};

static const SpsParamEntry s_spsParams_gta_vehicle_paint1[] = {
    { "SpecularColor", 0.15f },
    { "Specular", 180.0f },
    { "Specular2Factor", 40.0f },
    { "specular2ColorIntensity", 1.7f },
};

static const SpsParamEntry s_spsParams_gta_vehicle_paint2[] = {
    { "SpecularColor", 0.15f },
    { "Specular", 180.0f },
    { "Specular2Factor", 40.0f },
    { "specular2ColorIntensity", 1.7f },
};

static const SpsParamEntry s_spsParams_gta_vehicle_paint3[] = {
    { "SpecularColor", 0.15f },
    { "Specular", 180.0f },
    { "Specular2Factor", 40.0f },
    { "specular2ColorIntensity", 1.7f },
};

static const SpsParamEntry s_spsParams_gta_vehicle_rims1[] = {
    { "SpecularColor", 0.2f },
    { "Specular", 180.0f },
};

static const SpsParamEntry s_spsParams_gta_vehicle_rims1_alpha[] = {
    { "SpecularColor", 0.2f },
    { "Specular", 180.0f },
};

static const SpsParamEntry s_spsParams_gta_vehicle_rims2[] = {
    { "SpecularColor", 0.2f },
    { "Specular", 180.0f },
};

static const SpsParamEntry s_spsParams_gta_vehicle_shuts[] = {
    { "SpecularColor", 0.3f },
    { "Specular", 180.0f },
};

static const SpsParamEntry s_spsParams_gta_vehicle_vehglass[] = {
    { "SpecularColor", 0.15f },
    { "Specular", 180.0f },
};

static const SpsPresetEntry g_spsPresetTable[] = {
    { "gta_alpha.sps", "gta_default", 1, 0, nullptr },
    { "gta_cubemap_reflect.sps", "gta_cubemap_reflect", 0, 0, nullptr },
    { "gta_cutout.sps", "gta_default", 3, 0, nullptr },
    { "gta_cutout_fence.sps", "gta_cutout_fence", 3, 0, nullptr },
    { "gta_decal.sps", "gta_default", 2, 0, nullptr },
    { "gta_decal_amb_only.sps", "gta_decal_amb_only", 2, 0, nullptr },
    { "gta_decal_dirt.sps", "gta_decal_dirt", 2, 0, nullptr },
    { "gta_decal_glue.sps", "gta_decal_glue", 2, 0, nullptr },
    { "gta_decal_normal_only.sps", "gta_decal_normal_only", 2, 0, nullptr },
    { "gta_default.sps", "gta_default", 0, 0, nullptr },
    { "gta_diffuse_instance.sps", "gta_diffuse_instance", 0, 0, nullptr },
    { "gta_emissive.sps", "gta_emissive", 4, 0, nullptr },
    { "gta_emissive_alpha.sps", "gta_emissive", 5, 0, nullptr },
    { "gta_emissivenight.sps", "gta_emissivenight", 4, 0, nullptr },
    { "gta_emissivenight_alpha.sps", "gta_emissivenight", 5, 0, nullptr },
    { "gta_emissivestrong.sps", "gta_emissivestrong", 4, 0, nullptr },
    { "gta_emissivestrong_alpha.sps", "gta_emissivestrong", 5, 0, nullptr },
    { "gta_glass.sps", "gta_glass", 1, 0, nullptr },
    { "gta_glass_emissive.sps", "gta_glass_emissive", 4, 0, nullptr },
    { "gta_glass_emissive_alpha.sps", "gta_glass_emissive", 5, 0, nullptr },
    { "gta_glass_emissivenight.sps", "gta_glass_emissivenight", 4, 0, nullptr },
    { "gta_glass_emissivenight_alpha.sps", "gta_glass_emissivenight", 5, 0, nullptr },
    { "gta_glass_normal_spec_reflect.sps", "gta_glass_normal_spec_reflect", 1, 0, nullptr },
    { "gta_glass_reflect.sps", "gta_glass_reflect", 1, 0, nullptr },
    { "gta_glass_spec.sps", "gta_glass_spec", 1, 0, nullptr },
    { "gta_hair_sorted_alpha.sps", "gta_hair_sorted_alpha", 3, 0, nullptr },
    { "gta_hair_sorted_alpha_expensive.sps", "gta_hair_sorted_alpha_exp", 3, 0, nullptr },
    { "gta_leaves.sps", "gta_default", 0, 0, nullptr },
    { "gta_mirror.sps", "gta_reflect", 0, 0, nullptr },
    { "gta_normal.sps", "gta_normal", 0, 0, nullptr },
    { "gta_normal_alpha.sps", "gta_normal", 1, 0, nullptr },
    { "gta_normal_cubemap_reflect.sps", "gta_normal_cubemap_reflect", 0, 0, nullptr },
    { "gta_normal_cutout.sps", "gta_normal", 3, 0, nullptr },
    { "gta_normal_decal.sps", "gta_normal_decal", 2, 0, nullptr },
    { "gta_normal_reflect.sps", "gta_normal_reflect", 0, 0, nullptr },
    { "gta_normal_reflect_alpha.sps", "gta_normal_reflect", 1, 0, nullptr },
    { "gta_normal_reflect_decal.sps", "gta_normal_reflect_decal", 2, 0, nullptr },
    { "gta_normal_reflect_screendooralpha.sps", "gta_normal_reflect", 3, 0, nullptr },
    { "gta_normal_screendooralpha.sps", "gta_normal", 3, 0, nullptr },
    { "gta_normal_spec.sps", "gta_normal_spec", 0, 0, nullptr },
    { "gta_normal_spec_alpha.sps", "gta_normal_spec", 1, 0, nullptr },
    { "gta_normal_spec_cubemap_reflect.sps", "gta_normal_spec_cubemap_reflect", 0, 0, nullptr },
    { "gta_normal_spec_decal.sps", "gta_normal_spec_decal", 2, 0, nullptr },
    { "gta_normal_spec_reflect.sps", "gta_normal_spec_reflect", 0, 0, nullptr },
    { "gta_normal_spec_reflect_alpha.sps", "gta_normal_spec_reflect", 1, 0, nullptr },
    { "gta_normal_spec_reflect_decal.sps", "gta_normal_spec_reflect_decal", 2, 0, nullptr },
    { "gta_normal_spec_reflect_emissive.sps", "gta_normal_spec_reflect_emissive", 4, 0, nullptr },
    { "gta_normal_spec_reflect_emissive_alpha.sps", "gta_normal_spec_reflect_emissive", 5, 0, nullptr },
    { "gta_normal_spec_reflect_emissivenight.sps", "gta_normal_spec_reflect_emissivenight", 4, 0, nullptr },
    { "gta_normal_spec_reflect_emissivenight_alpha.sps", "gta_normal_spec_reflect_emissivenight", 5, 0, nullptr },
    { "gta_normal_spec_screendooralpha.sps", "gta_normal_spec", 3, 0, nullptr },
    { "gta_parallax.sps", "gta_parallax", 0, 0, nullptr },
    { "gta_parallax_specmap.sps", "gta_parallax_specmap", 0, 0, nullptr },
    { "gta_parallax_steep.sps", "gta_parallax_steep", 0, 0, nullptr },
    { "gta_ped.sps", "gta_ped", 0, 0, nullptr },
    { "gta_ped_alpha.sps", "gta_ped", 1, 0, nullptr },
    { "gta_ped_reflect.sps", "gta_ped_reflect", 0, 0, nullptr },
    { "gta_ped_reflect_alpha.sps", "gta_ped_reflect", 1, 0, nullptr },
    { "gta_ped_skin.sps", "gta_ped_skin", 0, 0, nullptr },
    { "gta_ped_skin_blendshape.sps", "gta_ped_skin_blendshape", 0, 0, nullptr },
    { "gta_radar.sps", "gta_radar", 0, 0, nullptr },
    { "gta_reflect.sps", "gta_reflect", 0, 0, nullptr },
    { "gta_reflect_alpha.sps", "gta_reflect", 1, 0, nullptr },
    { "gta_reflect_decal.sps", "gta_reflect", 2, 0, nullptr },
    { "gta_rmptfx_mesh.sps", "gta_rmptfx_mesh", 1, 0, nullptr },
    { "gta_spec.sps", "gta_spec", 0, 0, nullptr },
    { "gta_spec_alpha.sps", "gta_spec", 1, 0, nullptr },
    { "gta_spec_const.sps", "rage_default", 0, 0, nullptr },
    { "gta_spec_decal.sps", "gta_spec", 2, 0, nullptr },
    { "gta_spec_reflect.sps", "gta_spec_reflect", 0, 0, nullptr },
    { "gta_spec_reflect_alpha.sps", "gta_spec_reflect", 1, 0, nullptr },
    { "gta_spec_reflect_decal.sps", "gta_spec_reflect", 2, 0, nullptr },
    { "gta_spec_reflect_screendooralpha.sps", "gta_spec_reflect", 3, 0, nullptr },
    { "gta_spec_screendooralpha.sps", "gta_spec", 3, 0, nullptr },
    { "gta_terrain_va_2lyr.sps", "gta_terrain_va_2lyr", 0, 0, nullptr },
    { "gta_terrain_va_3lyr.sps", "gta_terrain_va_3lyr", 0, 0, nullptr },
    { "gta_terrain_va_4lyr.sps", "gta_terrain_va_4lyr", 0, 0, nullptr },
    { "gta_trees.sps", "gta_trees", 3, 0, nullptr },
    { "gta_vehicle.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_badges.sps", "gta_vehicle_badges", 1, 0, nullptr },
    { "gta_vehicle_basic.sps", "gta_vehicle_basic", 0, 0, nullptr },
    { "gta_vehicle_chrome.sps", "gta_vehicle_chrome", 0, 2, s_spsParams_gta_vehicle_chrome },
    { "gta_vehicle_default.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_default_2lyr.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_default_2lyr_dmg.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_default_dmg.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_disc.sps", "gta_vehicle_disc", 1, 0, nullptr },
    { "gta_vehicle_generic.sps", "gta_vehicle_generic", 0, 0, nullptr },
    { "gta_vehicle_glass.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_glass_dmg.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_glass_emissive.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_interior.sps", "gta_vehicle_interior", 0, 0, nullptr },
    { "gta_vehicle_interior2.sps", "gta_vehicle_interior2", 0, 0, nullptr },
    { "gta_vehicle_lights.sps", "gta_vehicle_vehglass", 1, 0, nullptr },
    { "gta_vehicle_lightsemissive.sps", "gta_vehicle_lightsemissive", 1, 0, nullptr },
    { "gta_vehicle_mesh.sps", "gta_vehicle_mesh", 0, 0, nullptr },
    { "gta_vehicle_nosplash.sps", "gta_vehicle_paint1", 29, 0, nullptr },
    { "gta_vehicle_nowater.sps", "gta_vehicle_paint1", 30, 0, nullptr },
    { "gta_vehicle_paint1.sps", "gta_vehicle_paint1", 0, 4, s_spsParams_gta_vehicle_paint1 },
    { "gta_vehicle_paint2.sps", "gta_vehicle_paint2", 0, 4, s_spsParams_gta_vehicle_paint2 },
    { "gta_vehicle_paint3.sps", "gta_vehicle_paint3", 0, 4, s_spsParams_gta_vehicle_paint3 },
    { "gta_vehicle_rims1.sps", "gta_vehicle_rims1", 0, 2, s_spsParams_gta_vehicle_rims1 },
    { "gta_vehicle_rims1_alpha.sps", "gta_vehicle_rims1", 3, 2, s_spsParams_gta_vehicle_rims1_alpha },
    { "gta_vehicle_rims2.sps", "gta_vehicle_rims2", 0, 2, s_spsParams_gta_vehicle_rims2 },
    { "gta_vehicle_rubber.sps", "gta_vehicle_rubber", 0, 0, nullptr },
    { "gta_vehicle_shuts.sps", "gta_vehicle_shuts", 0, 2, s_spsParams_gta_vehicle_shuts },
    { "gta_vehicle_spec.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_2lyr.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_2lyr_dmg.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_bump.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_bump_dmg.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_dmg.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect_2lyr.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect_2lyr_dmg.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect_alpha.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect_alpha_dmg.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect_bump.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect_bump_2lyr.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect_bump_2lyr_dmg.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect_bump_alpha_dmg.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect_bump_dmg.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect_bumpuv.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect_bumpuv_2lyr.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect_bumpuv_2lyr_dmg.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect_bumpuv_dmg.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_spec_reflect_dmg.sps", "gta_default", 0, 0, nullptr },
    { "gta_vehicle_tire.sps", "gta_vehicle_tire", 0, 0, nullptr },
    { "gta_vehicle_vehglass.sps", "gta_vehicle_vehglass", 1, 2, s_spsParams_gta_vehicle_vehglass },
    { "gta_wire.sps", "gta_wire", 1, 0, nullptr },
    { "rage_billboard_nobump.sps", "rage_billboard_nobump", 0, 0, nullptr },
};

static const size_t g_spsPresetTableCount = 131;
