if(NOT CMAKE_SYSTEM_NAME STREQUAL "iOS" OR NOT APPLE)
    message(FATAL_ERROR "The iOS core requires an iOS toolchain and an Apple SDK")
endif()
if(NOT CMAKE_OSX_ARCHITECTURES STREQUAL "arm64")
    message(FATAL_ERROR "The experimental iOS core currently supports arm64 only")
endif()
if(NOT CMAKE_OSX_SYSROOT MATCHES "(iphoneos|iphonesimulator|iPhoneOS|iPhoneSimulator)")
    message(FATAL_ERROR "Select the iphoneos or iphonesimulator SDK")
endif()
