#pragma once

#include <cstddef>
#include <cstdint>

struct theft4_ios_audio_output;

// Creates a 48 kHz stereo iOS playback path backed by a real-time-safe ring.
// Submitted blocks contain the Xbox mixer's six sequential, big-endian float
// channels (256 frames each).
theft4_ios_audio_output* theft4_ios_audio_output_create();
void theft4_ios_audio_output_destroy(theft4_ios_audio_output* output);
bool theft4_ios_audio_output_submit(theft4_ios_audio_output* output,
                                    const float* guest_samples,
                                    size_t guest_frame_count);

// Returns the absolute number of guest mixer blocks the producer should have
// generated by now. The target begins with an iOS reliability preroll and is
// advanced by the real audio callback as blocks are consumed.
uint64_t theft4_ios_audio_output_requested_blocks(
    const theft4_ios_audio_output* output);
