#pragma once

#include <cstdint>
#include <cstddef>

struct ShaderCacheEntry
{
    const uint64_t hash;
    const uint32_t dxilOffset;
    const uint32_t dxilSize;
    const uint32_t spirvOffset;
    const uint32_t spirvSize;
    const uint32_t lateSpirvOffset;
    const uint32_t lateSpirvSize;
    const uint32_t airOffset;
    const uint32_t airSize;
    const uint32_t specConstantsMask;
    char filename[256];
    struct GuestShader* guestShader;
    // Xenos texture-fetch constant slots referenced by the guest microcode.
    // This is deliberately stored after guestShader so a checked-in cache
    // generated by the preceding schema remains source-compatible until the
    // complete shader corpus is regenerated. The sentinel makes a legacy
    // entry fail closed instead of being mistaken for a shader that samples
    // no textures.
    const uint32_t usedTextureMask = UINT32_MAX;
};

extern ShaderCacheEntry g_shaderCacheEntries[];
extern const size_t g_shaderCacheEntryCount;

extern const uint8_t g_compressedDxilCache[];
extern const size_t g_dxilCacheCompressedSize;
extern const size_t g_dxilCacheDecompressedSize;

extern const uint8_t g_compressedAirCache[];
extern const size_t g_airCacheCompressedSize;
extern const size_t g_airCacheDecompressedSize;

extern const uint8_t g_compressedSpirvCache[];
extern const size_t g_spirvCacheCompressedSize;
extern const size_t g_spirvCacheDecompressedSize;
